# Generated by Django 3.1.7 on 2021-03-16 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Date creation'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_b64',
            field=models.TextField(null=True),
        ),
    ]
